# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* test_exceptions
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server GreenOdoo-trunk-wms-20140425-"
"linux-34ff97d-599b23a-16a05eb\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-11-24 21:44+0800\n"
"PO-Revision-Date: 2015-11-24 21:46+0800\n"
"Last-Translator: 保定-粉刷匠 <openerp@126.com>\n"
"Language-Team: \n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: \n"
"X-Generator: Poedit 1.8.6\n"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Access denied-traceback"
msgstr "存取被拒绝-向前追溯"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Access rights error-description"
msgstr "存取权限错误-描述"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "AccessDenied"
msgstr "存取被拒绝"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "AccessDenied*"
msgstr "存取被拒绝*"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "AccessError"
msgstr "存取错误"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "AccessError*"
msgstr "存取错误*"

#. module: test_exceptions
#: model:ir.model.fields,field_description:test_exceptions.field_test_exceptions_model_create_uid
msgid "Created by"
msgstr "创建者"

#. module: test_exceptions
#: model:ir.model.fields,field_description:test_exceptions.field_test_exceptions_model_create_date
msgid "Created on"
msgstr "创建时间"

#. module: test_exceptions
#: model:ir.model.fields,field_description:test_exceptions.field_test_exceptions_model_display_name
msgid "Display Name"
msgstr "显示名称"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid ""
"Each button generates a specific exception on the server. The text on the "
"right is the expected representation of the exception when displayed on the "
"client. Button marked with a '*' use safe_eval()."
msgstr ""
"每一个按钮在服务器上产生一个特定的异常。右边的文本是期望显示在客户端上的异常"
"提示。按钮被标记上“*”表示使用safe_eval()。"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Exc AccessDenied"
msgstr "执行存取拒绝"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Exc AccessDenied*"
msgstr "执行存取拒绝*"

#. module: test_exceptions
#: model:ir.model.fields,field_description:test_exceptions.field_test_exceptions_model_id
msgid "ID"
msgstr "ID"

#. module: test_exceptions
#: model:ir.model.fields,field_description:test_exceptions.field_test_exceptions_model___last_update
msgid "Last Modified on"
msgstr "最近修改日期"

#. module: test_exceptions
#: model:ir.model.fields,field_description:test_exceptions.field_test_exceptions_model_write_uid
msgid "Last Updated by"
msgstr "最后修改人"

#. module: test_exceptions
#: model:ir.model.fields,field_description:test_exceptions.field_test_exceptions_model_write_date
msgid "Last Updated on"
msgstr "最后更新日期"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Missing Error-description"
msgstr "丢失错误-描述"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "MissingError"
msgstr "丢失错误"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "MissingError*"
msgstr "丢失错误*"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "RedirectWarning"
msgstr "重指向警告"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "RedirectWarning*"
msgstr "重指向警告*"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Server error-traceback"
msgstr "服务器错误追踪"

#. module: test_exceptions
#: model:ir.actions.act_window,name:test_exceptions.action_test_exceptions
#: model:ir.ui.menu,name:test_exceptions.menu_test_exceptions
#: model:ir.ui.menu,name:test_exceptions.menu_test_exceptions_leaf
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Test exceptions"
msgstr "测试异常"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Undefined"
msgstr "未定义"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Undefined*"
msgstr "未定义*"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "UserError"
msgstr "用户错误"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "UserError*"
msgstr "用户错误*"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Validation Error-description"
msgstr "校验错误-描述"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "ValidationError"
msgstr "校验错误"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "ValidationError*"
msgstr "校验错误*"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Warning"
msgstr "警告"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Warning*"
msgstr "警告*"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Warning-description"
msgstr "警告-描述"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "Warning-description-redirection button"
msgstr "警告-描述-重定向 按钮"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "except_orm"
msgstr "except_orm"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "except_orm*"
msgstr "except_orm*"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "except_osv"
msgstr "except_osv"

#. module: test_exceptions
#: model:ir.ui.view,arch_db:test_exceptions.view_test_exceptions_model
msgid "except_osv*"
msgstr "except_osv*"

#. module: test_exceptions
#: model:ir.model,name:test_exceptions.model_test_exceptions_model
msgid "test.exceptions.model"
msgstr "test.exceptions.model"
